/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/page/About.vue')['default']
    AboutLayout: typeof import('./src/page/AboutLayout.vue')['default']
    AboutYou: typeof import('./src/page/AboutYou.vue')['default']
    AuthLayout: typeof import('./src/page/AuthLayout.vue')['default']
    AuthLogin: typeof import('./src/page/AuthLogin.vue')['default']
    AuthRegister: typeof import('./src/page/AuthRegister.vue')['default']
    BookLayout: typeof import('./src/page/BookLayout.vue')['default']
    BookList: typeof import('./src/page/BookList.vue')['default']
    ErrorNotFound: typeof import('./src/page/ErrorNotFound.vue')['default']
    Home: typeof import('./src/page/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
