/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarLeft: typeof import('./../src/component/bar/bar-left.vue')['default']
    BarTop: typeof import('./../src/component/bar/bar-top.vue')['default']
    Bnotification: typeof import('./../src/component/notification/bnotification.vue')['default']
    BnotificationList: typeof import('./../src/component/notification/bnotification-list.vue')['default']
    Bpage: typeof import('./../src/component/bpage.vue')['default']
    Default: typeof import('./../src/layout/default.vue')['default']
    LayoutDefault: typeof import('./../src/layout/layout-default.vue')['default']
    NotificationList: typeof import('./../src/component/notification-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./../src/component/bar/top-bar.vue')['default']
  }
}
